name: check-mvn
on: 
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build and Test with Maven
        run: mvn --no-transfer-progress test
      - name: Run JUnit Console Standalone
        run: mvn --no-transfer-progress exec:java
      - name: Check for Checkstyle Warnings
        run: mvn --no-transfer-progress -Dcheckstyle.violationSeverity=warning compile
